# Generated by Django 3.0.5 on 2023-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=25)),
                ('donor_password', models.CharField(max_length=25)),
                ('donor_postal', models.CharField(max_length=10)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_bio_sex', models.CharField(max_length=25)),
                ('donor_blood_type', models.CharField(max_length=10)),
                ('donor_birthday', models.DateField(auto_now=True)),
                ('donor_weight', models.PositiveIntegerField(default=0)),
                ('donor_height', models.PositiveIntegerField(default=0)),
                ('donor_contact_phone', models.CharField(max_length=25)),
                ('emergency_contact_name', models.CharField(max_length=25)),
                ('emergency_contact_phone', models.CharField(max_length=25)),
            ],
        ),
    ]
