# Generated by Django 3.0.5 on 2023-03-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20230304_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
