# Generated by Django 3.0.5 on 2023-03-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20230307_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
