# Generated by Django 3.0.5 on 2023-03-08 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('donor', '0003_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('donor_first_name', models.CharField(max_length=25)),
                ('donor_last_name', models.CharField(max_length=25)),
                ('donor_postal', models.CharField(max_length=10)),
                ('donor_email', models.CharField(max_length=20)),
                ('donor_bio_sex', models.CharField(max_length=25)),
                ('donor_blood_type', models.CharField(max_length=10)),
                ('donor_birthday', models.DateField(null=True)),
                ('donor_weight', models.PositiveIntegerField(default=0)),
                ('donor_height', models.PositiveIntegerField(default=0)),
                ('donor_contact_phone', models.CharField(max_length=25)),
                ('emergency_contact_name', models.CharField(max_length=25)),
                ('emergency_contact_phone', models.CharField(max_length=25)),
                ('donor_nextdonationdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
