# Generated by Django 3.0.5 on 2023-03-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20230308_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_email',
        ),
    ]
