# Generated by Django 3.0.5 on 2023-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_remove_donor_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_contact_phone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='emergency_contact_phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
