# Generated by Django 3.0.5 on 2023-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_auto_20230313_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
