# Generated by Django 3.0.5 on 2023-03-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20230227_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='edonor_email',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
