# Generated by Django 2.2.3 on 2023-03-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_events_edonor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='edonor_blood',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='events',
            name='edonor_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
