# Generated by Django 2.2.3 on 2023-02-28 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=25)),
                ('apptname', models.CharField(max_length=25)),
                ('elocation', models.CharField(max_length=25)),
                ('eaddress', models.CharField(max_length=25)),
                ('epscode', models.CharField(max_length=25)),
                ('edate', models.DateField(default=datetime.date(1990, 1, 1))),
                ('etimest', models.CharField(max_length=25)),
                ('etimend', models.CharField(max_length=25)),
            ],
        ),
    ]
