# Generated by Django 2.2.3 on 2023-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20230227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='edate',
            field=models.CharField(max_length=25),
        ),
    ]
